#!/usr/bin/env bash
#
# common.sh - shared step engine for the guided UAT walkthroughs beside it.
#
# Source this from a per-guide script (see any <command>.sh); do not run it
# directly. It turns a markdown UAT guide into an executable walkthrough: each
# step prints why it exists, echoes and runs the guide's exact command, shows
# the real output and the observed vs expected exit code, asserts the guide's
# expectation, and then waits for a keypress before the next step.
#
# This file is project-agnostic. Project values - a connection file, a fixture
# seeder, an extra flag - belong in project.sh beside it, which this library
# sources when present. Do not edit this file to add them.
#
# Exit codes a consuming script should use (via uat_summary / uat_fatal):
#   0 - every executed assertion passed
#   1 - at least one assertion failed
#   2 - bad invocation (unknown flag, missing value, out-of-range step)
#   3 - a prerequisite is missing (tool, file, or a fixture)
# 130 - interrupted by the operator
#
# Deliberately NOT `set -e`: several UAT steps run commands that are expected to
# exit non-zero (a lookup miss exits 1, an unparseable id exits 2). Errexit would
# abort the walkthrough at the first such step. Consuming scripts use
# `set -uo pipefail` and let uat_run capture each exit code explicitly.

# Refuse direct execution: this file only defines functions.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    printf 'common.sh is a library; source it from a UAT script instead:\n' >&2
    printf '    source "$(dirname "${BASH_SOURCE[0]}")/common.sh"\n' >&2
    printf 'To run a guided walkthrough, use e.g.: ./<command>.sh --help\n' >&2
    exit 2
fi

# Sourcing twice must not re-declare the readonly constants below.
if [[ -n "${UAT_COMMON_SOURCED:-}" ]]; then
    return 0
fi
UAT_COMMON_SOURCED=1

readonly UAT_EXIT_OK=0
readonly UAT_EXIT_FAIL=1
readonly UAT_EXIT_USAGE=2
readonly UAT_EXIT_PREREQ=3

# Directory holding this library, resolved before any cd.
UAT_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors only when stdout is a terminal, so a tee'd log stays plain text.
if [[ -t 1 ]]; then
    UAT_RED=$'\033[0;31m'
    UAT_GREEN=$'\033[0;32m'
    UAT_YELLOW=$'\033[1;33m'
    UAT_BOLD=$'\033[1m'
    UAT_NC=$'\033[0m'
else
    UAT_RED=''
    UAT_GREEN=''
    UAT_YELLOW=''
    UAT_BOLD=''
    UAT_NC=''
fi

# ---------------------------------------------------------------------------
# Failure reporting
# ---------------------------------------------------------------------------

# uat_fatal <exit_code> <message...>
# Print a message to stderr and exit immediately. Used for prerequisite and
# invocation failures, never for a failed step assertion (those are recorded and
# the walkthrough continues).
uat_fatal() {
    local code="$1"
    shift
    printf '%sERROR%s %s\n' "$UAT_RED" "$UAT_NC" "$*" >&2
    exit "$code"
}

# uat_require_cmd <command> <hint>
# Exit 3 naming the fix when <command> is not on PATH.
uat_require_cmd() {
    local cmd="$1" hint="$2"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        uat_fatal "$UAT_EXIT_PREREQ" "'$cmd' is not on PATH. $hint"
    fi
}

# uat_require_file <path> <hint>
# Exit 3 naming the fix when <path> does not exist.
uat_require_file() {
    local path="$1" hint="$2"
    if [[ ! -f "$path" ]]; then
        uat_fatal "$UAT_EXIT_PREREQ" "file not found: $path. $hint"
    fi
}

# uat_require_dir <path> <hint>
# Exit 3 naming the fix when <path> is not a directory.
uat_require_dir() {
    local path="$1" hint="$2"
    if [[ ! -d "$path" ]]; then
        uat_fatal "$UAT_EXIT_PREREQ" "directory not found: $path. $hint"
    fi
}

# ---------------------------------------------------------------------------
# Initialization and shared flags
# ---------------------------------------------------------------------------

# Walk up from the library directory to the nearest checkout root, so a guide
# runs from the same working directory whatever path the operator invoked it by.
# project.sh may set UAT_REPO_ROOT itself to override this.
_uat_find_repo_root() {
    local dir="$UAT_LIB_DIR" parent
    while [[ -n "$dir" ]]; do
        if [[ -e "$dir/.git" ]]; then
            printf '%s' "$dir"
            return 0
        fi
        parent="$(dirname "$dir")"
        [[ "$parent" == "$dir" ]] && break
        dir="$parent"
    done
    printf '%s' "$UAT_LIB_DIR"
}

# uat_init
# Anchor the run at the checkout root and set every shared default. Call once,
# before uat_parse_common_args.
uat_init() {
    if [[ -z "${UAT_REPO_ROOT:-}" ]]; then
        UAT_REPO_ROOT="$_UAT_DEFAULT_REPO_ROOT"
    fi
    cd "$UAT_REPO_ROOT" || uat_fatal "$UAT_EXIT_PREREQ" "cannot enter repo root $UAT_REPO_ROOT"

    # Behavior toggles, all settable through the shared flags.
    UAT_PAUSE=1
    UAT_STOP_ON_FAIL=0
    UAT_DO_SEED=0
    UAT_DO_CLEANUP=0
    UAT_KEEP_OUTPUT=0
    UAT_LIST_ONLY=0
    UAT_FROM_STEP=""
    UAT_ONLY_STEP=""

    # Interpreter used by uat_assert_json_file. Override in project.sh, e.g.
    # UAT_PYTHON_CMD=(uv run python).
    if [[ -z "${UAT_PYTHON_CMD+x}" ]]; then
        if command -v python3 >/dev/null 2>&1; then
            UAT_PYTHON_CMD=(python3)
        else
            UAT_PYTHON_CMD=(python)
        fi
    fi

    # State written by uat_run and read by the assertion helpers.
    UAT_OUT=""
    UAT_RC=0

    # Counters reported by uat_summary.
    UAT_STEP_NO=0
    UAT_TOTAL_STEPS=0
    UAT_PASS_COUNT=0
    UAT_FAIL_COUNT=0
    UAT_STEPS_RUN=0
    UAT_STEPS_FAILED=0
    UAT_STEPS_SKIPPED=0
    UAT_STEP_FAILED=0
    UAT_STEP_SKIPPED=0
    UAT_PARTIAL=0

    # Step range resolved by uat_resolve_range and consumed by uat_run_steps.
    UAT_FIRST_STEP=0
    UAT_LAST_STEP=0

    UAT_REST=()
    UAT_ARG_CONSUMED=0

    # Project defaults last, so they can override anything above.
    if declare -F uat_project_defaults >/dev/null 2>&1; then
        uat_project_defaults
    fi

    trap 'printf "\ninterrupted\n" >&2; exit 130' INT
}

# uat_parse_common_args "$@"
# Consume the flags every UAT script shares. Anything project.sh claims through
# uat_project_parse_arg is consumed there; whatever is left lands in the UAT_REST
# array for the caller to reject or interpret. Exits 2 on a missing flag value.
uat_parse_common_args() {
    UAT_REST=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --auto | --no-pause)
                UAT_PAUSE=0
                ;;
            --stop-on-fail)
                UAT_STOP_ON_FAIL=1
                ;;
            --seed)
                UAT_DO_SEED=1
                ;;
            --cleanup)
                UAT_DO_CLEANUP=1
                ;;
            --keep-output)
                UAT_KEEP_OUTPUT=1
                ;;
            --list-steps)
                UAT_LIST_ONLY=1
                ;;
            --from-step)
                [[ $# -ge 2 ]] || uat_fatal "$UAT_EXIT_USAGE" "--from-step needs a step number"
                UAT_FROM_STEP="$2"
                shift
                ;;
            --only-step)
                [[ $# -ge 2 ]] || uat_fatal "$UAT_EXIT_USAGE" "--only-step needs a step number"
                UAT_ONLY_STEP="$2"
                shift
                ;;
            *)
                UAT_ARG_CONSUMED=0
                if declare -F uat_project_parse_arg >/dev/null 2>&1; then
                    uat_project_parse_arg "$@"
                fi
                if [[ "$UAT_ARG_CONSUMED" -gt 0 ]]; then
                    shift $((UAT_ARG_CONSUMED - 1))
                else
                    UAT_REST+=("$1")
                fi
                ;;
        esac
        shift
    done

    # An environment opt-out for unattended runs, equivalent to --auto.
    if [[ "${UAT_AUTO:-0}" == "1" ]]; then
        UAT_PAUSE=0
    fi

    # Give the project a chance to recompose anything derived from a flag it
    # just parsed (a connection string built from --properties, for instance).
    if declare -F uat_project_after_args >/dev/null 2>&1; then
        uat_project_after_args
    fi
}

# uat_require_step_number <flag> <value> <max>
# Validate a --from-step / --only-step value; exits 2 when it is not an integer
# in 0..<max>.
uat_require_step_number() {
    local flag="$1" value="$2" max="$3"
    if [[ ! "$value" =~ ^[0-9]+$ ]] || [[ "$value" -gt "$max" ]]; then
        uat_fatal "$UAT_EXIT_USAGE" "$flag: '$value' is not a step number in 0..$max"
    fi
}

# ---------------------------------------------------------------------------
# Printing
# ---------------------------------------------------------------------------

uat_rule() {
    printf -- '--------------------------------------------------------------------\n'
}

# uat_banner <title...>
uat_banner() {
    printf '\n'
    printf '====================================================================\n'
    printf '%s%s%s\n' "$UAT_BOLD" "$*" "$UAT_NC"
    printf '====================================================================\n'
}

# Wrap free text to a readable width, indented two spaces. `fold` ships with Git
# Bash and every POSIX userland; fall back to unwrapped output if it is missing.
_uat_wrap() {
    if command -v fold >/dev/null 2>&1; then
        printf '%s\n' "$*" | fold -s -w 74 | sed 's/^/  /'
    else
        printf '  %s\n' "$*"
    fi
}

# uat_step <number> <title...>
# Open the step: rule, numbered title, and reset of the per-step flags.
uat_step() {
    local number="$1"
    shift
    UAT_STEP_NO="$number"
    UAT_STEP_FAILED=0
    UAT_STEP_SKIPPED=0
    UAT_STEPS_RUN=$((UAT_STEPS_RUN + 1))
    printf '\n'
    uat_rule
    printf '%sStep %s/%s: %s%s\n' "$UAT_BOLD" "$number" "$UAT_TOTAL_STEPS" "$*" "$UAT_NC"
    uat_rule
}

# uat_explain <text...>  - why this step exists and what it proves.
uat_explain() {
    printf 'Why:\n'
    _uat_wrap "$*"
    printf '\n'
}

# uat_expect <text...>   - the guide's own "what to check" wording.
uat_expect() {
    printf 'Expect:\n'
    _uat_wrap "$*"
}

# uat_note <text...>     - an aside that is neither an explanation nor a check.
uat_note() {
    printf '%sNote:%s\n' "$UAT_YELLOW" "$UAT_NC"
    _uat_wrap "$*"
}

# Render one argument for the echoed command line: quote it when it carries
# whitespace, a shell metacharacter, or is empty, so the printed line is
# copy-pasteable.
_uat_display_arg() {
    local arg="$1"
    if [[ -z "$arg" || "$arg" =~ [[:space:]\;\"\$\*\&\|\<\>] ]]; then
        printf '"%s"' "$arg"
    else
        printf '%s' "$arg"
    fi
}

# uat_show_command <command> [args...]
uat_show_command() {
    local rendered="" arg
    for arg in "$@"; do
        rendered+="$(_uat_display_arg "$arg") "
    done
    printf 'Command:\n'
    printf '  %s\n' "${rendered% }"
}

# ---------------------------------------------------------------------------
# Running and asserting
# ---------------------------------------------------------------------------

# uat_run <expected_exit> <command> [args...]
# Echo the command, run it capturing combined output into UAT_OUT and the status
# into UAT_RC, print the output block and the observed vs expected exit line, and
# record the exit-code assertion. Never aborts on a non-zero status: the expected
# status of several UAT steps is non-zero.
uat_run() {
    local expected="$1"
    shift
    uat_show_command "$@"
    printf '\n'
    UAT_OUT="$("$@" 2>&1)"
    UAT_RC=$?
    printf -- '--- output ---\n'
    printf '%s\n' "$UAT_OUT"
    printf -- '--- exit code: %s (expected %s) ---\n\n' "$UAT_RC" "$expected"
    uat_assert_exit "$expected"
}

# uat_run_quiet <command> [args...]
# Same capture, no printing and no assertion. For preparatory calls whose output
# is not part of the walkthrough (e.g. deriving a value a later step needs).
uat_run_quiet() {
    UAT_OUT="$("$@" 2>&1)"
    UAT_RC=$?
    return 0
}

# uat_pass / uat_fail <message...>
# Record an assertion result directly. Used by the uat_assert_* helpers, and by a
# step whose check is not a simple match against captured output.
uat_pass() {
    UAT_PASS_COUNT=$((UAT_PASS_COUNT + 1))
    printf '  %s[PASS]%s %s\n' "$UAT_GREEN" "$UAT_NC" "$*"
}

uat_fail() {
    UAT_FAIL_COUNT=$((UAT_FAIL_COUNT + 1))
    if [[ "$UAT_STEP_FAILED" -eq 0 ]]; then
        UAT_STEP_FAILED=1
        UAT_STEPS_FAILED=$((UAT_STEPS_FAILED + 1))
    fi
    printf '  %s[FAIL]%s %s\n' "$UAT_RED" "$UAT_NC" "$*"
}

# uat_skip <reason...>
# Record that this step did not run, and why. Call it instead of the step's
# command, after uat_step (and usually after uat_explain / uat_expect) so the
# operator still reads what the step would have proved.
#
# A skip is not a pass and not a failure: it never touches the assertion counts
# or the exit code. It moves the step from "run" to "skipped" so the summary
# cannot present a walkthrough that mostly did not happen as a clean pass.
uat_skip() {
    if [[ "$UAT_STEP_SKIPPED" -eq 0 ]]; then
        UAT_STEP_SKIPPED=1
        UAT_STEPS_SKIPPED=$((UAT_STEPS_SKIPPED + 1))
        if [[ "$UAT_STEPS_RUN" -gt 0 ]]; then
            UAT_STEPS_RUN=$((UAT_STEPS_RUN - 1))
        fi
    fi
    printf '  %s[SKIP]%s %s\n' "$UAT_YELLOW" "$UAT_NC" "$*"
}

# uat_have_cmd <command>
# Non-fatal counterpart to uat_require_cmd: true when <command> is on PATH,
# false otherwise, with no output and no exit. For an optional dependency whose
# absence should skip a step rather than end the walkthrough.
uat_have_cmd() {
    command -v "$1" >/dev/null 2>&1
}

# uat_latest_file <glob>
# Print the most recently modified file matching <glob>, or nothing when the
# pattern matches no file. Pass the pattern quoted - it is expanded here, not by
# the caller, so a no-match yields empty output instead of the literal pattern.
#
# This is the scripted form of the `ls -t ... | head -1` the guides use to chain
# one command's newest artifact into the next.
uat_latest_file() {
    local pattern="$1"
    local newest="" candidate had_nullglob=0
    shopt -q nullglob && had_nullglob=1
    shopt -s nullglob
    for candidate in $pattern; do
        [[ -f "$candidate" ]] || continue
        if [[ -z "$newest" || "$candidate" -nt "$newest" ]]; then
            newest="$candidate"
        fi
    done
    [[ "$had_nullglob" -eq 1 ]] || shopt -u nullglob
    printf '%s' "$newest"
}

# uat_assert_exit <expected>
uat_assert_exit() {
    local expected="$1"
    if [[ "$UAT_RC" -eq "$expected" ]]; then
        uat_pass "exit code is $expected"
    else
        uat_fail "exit code is $UAT_RC, expected $expected"
    fi
}

# uat_assert_contains <needle> [label]
# Literal substring check against the captured output.
uat_assert_contains() {
    local needle="$1"
    local label="${2:-output contains '$needle'}"
    if [[ "$UAT_OUT" == *"$needle"* ]]; then
        uat_pass "$label"
    else
        uat_fail "$label"
    fi
}

# uat_assert_not_contains <needle> [label]
uat_assert_not_contains() {
    local needle="$1"
    local label="${2:-output does not contain '$needle'}"
    if [[ "$UAT_OUT" == *"$needle"* ]]; then
        uat_fail "$label"
    else
        uat_pass "$label"
    fi
}

# uat_assert_matches <extended_regex> [label]
# Regex check, used where a report pads a label to a fixed width so the exact
# run of spaces is not worth hardcoding.
uat_assert_matches() {
    local pattern="$1"
    local label="${2:-output matches /$pattern/}"
    if printf '%s\n' "$UAT_OUT" | grep -Eq -- "$pattern"; then
        uat_pass "$label"
    else
        uat_fail "$label"
    fi
}

# uat_assert_file_exists <file> [label]
uat_assert_file_exists() {
    local file="$1"
    local label="${2:-$file exists}"
    if [[ -f "$file" ]]; then
        uat_pass "$label"
    else
        uat_fail "$label"
    fi
}

# uat_assert_file_contains <file> <needle> [label]
uat_assert_file_contains() {
    local file="$1" needle="$2"
    local label="${3:-$file contains '$needle'}"
    if [[ -f "$file" ]] && grep -qF -- "$needle" "$file"; then
        uat_pass "$label"
    else
        uat_fail "$label"
    fi
}

# uat_assert_json_file <file> <key> [key...]
# Assert the file parses as JSON and carries every named top-level key. Parses
# rather than greps, so a malformed document cannot pass. Uses UAT_PYTHON_CMD.
uat_assert_json_file() {
    local file="$1"
    shift
    local keys="$*"
    if [[ ! -f "$file" ]]; then
        uat_fail "$file exists and is JSON with keys: $keys"
        return
    fi
    if "${UAT_PYTHON_CMD[@]}" -c "import json,sys; d=json.load(open(sys.argv[1], encoding='utf-8')); missing=[k for k in sys.argv[2:] if k not in d]; sys.exit(1 if missing else 0)" "$file" "$@" >/dev/null 2>&1; then
        uat_pass "$file is JSON with keys: $keys"
    else
        uat_fail "$file is JSON with keys: $keys"
    fi
}

# ---------------------------------------------------------------------------
# Pausing
# ---------------------------------------------------------------------------

# uat_pause
# Block until a single keypress. Skipped under --auto / UAT_AUTO=1, and whenever
# no terminal is attached, so a piped or redirected run never hangs.
uat_pause() {
    [[ "$UAT_PAUSE" -eq 1 ]] || return 0
    [[ -r /dev/tty ]] || return 0
    printf '\n%sPress any key to continue . . .%s' "$UAT_YELLOW" "$UAT_NC"
    # A closed or non-responding tty makes read fail; that must not be mistaken
    # for a step failure, hence the guard.
    read -rsn 1 </dev/tty || true
    printf '\n'
}

# ---------------------------------------------------------------------------
# Fixtures
#
# Default no-ops so a guide that needs no fixture can still accept --seed and
# --cleanup. A project that does have one overrides both in project.sh.
# ---------------------------------------------------------------------------

uat_seed() {
    printf 'No fixture seeder is defined for this project (see project.sh).\n'
}

uat_cleanup() {
    printf 'No fixture cleanup is defined for this project (see project.sh).\n'
}

# ---------------------------------------------------------------------------
# Step index and the step loop
# ---------------------------------------------------------------------------

# uat_list_steps <script_name>
# Print the step index out of the STEP_TITLES array the guide script declares.
uat_list_steps() {
    printf 'Steps in %s:\n\n' "$1"
    local index=0
    while [[ $index -lt ${#STEP_TITLES[@]} ]]; do
        printf '  %2s  %s\n' "$index" "${STEP_TITLES[$index]}"
        index=$((index + 1))
    done
}

# uat_resolve_range <last_step>
# Turn --from-step / --only-step into UAT_FIRST_STEP..UAT_LAST_STEP, marking the
# run partial whenever the range is not the whole walkthrough. Exits 2 on a value
# that is not a step number.
uat_resolve_range() {
    local last="$1"
    UAT_FIRST_STEP=0
    UAT_LAST_STEP="$last"
    if [[ -n "$UAT_ONLY_STEP" ]]; then
        uat_require_step_number "--only-step" "$UAT_ONLY_STEP" "$last"
        UAT_FIRST_STEP="$UAT_ONLY_STEP"
        UAT_LAST_STEP="$UAT_ONLY_STEP"
        UAT_PARTIAL=1
    elif [[ -n "$UAT_FROM_STEP" ]]; then
        uat_require_step_number "--from-step" "$UAT_FROM_STEP" "$last"
        UAT_FIRST_STEP="$UAT_FROM_STEP"
        [[ "$UAT_FIRST_STEP" -eq 0 ]] || UAT_PARTIAL=1
    fi
}

# uat_run_steps
# Call step_<n> across the resolved range, pausing between steps and honoring
# --stop-on-fail. Call uat_resolve_range first.
uat_run_steps() {
    local index="$UAT_FIRST_STEP" ran_any=0
    while [[ "$index" -le "$UAT_LAST_STEP" ]]; do
        [[ "$ran_any" -eq 0 ]] || uat_pause
        "step_$index"
        ran_any=1
        if [[ "$UAT_STOP_ON_FAIL" -eq 1 && "$UAT_STEP_FAILED" -eq 1 ]]; then
            printf '\n%sstopping at step %s (--stop-on-fail)%s\n' "$UAT_YELLOW" "$index" "$UAT_NC"
            UAT_PARTIAL=1
            break
        fi
        index=$((index + 1))
    done
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

# uat_summary
# Print the totals and return the script's exit code (0 all passed, 1 otherwise).
#
# A skipped step never changes that exit code - an absent optional tool is not a
# test failure - but it does qualify the RESULT line, so a run that mostly did
# not happen can never be read as a clean pass.
uat_summary() {
    printf '\n'
    printf '====================================================================\n'
    printf '%sSummary%s\n' "$UAT_BOLD" "$UAT_NC"
    printf '  steps run     : %s\n' "$UAT_STEPS_RUN"
    printf '  steps skipped : %s\n' "$UAT_STEPS_SKIPPED"
    printf '  steps failed  : %s\n' "$UAT_STEPS_FAILED"
    printf '  assertions    : %s passed, %s failed\n' "$UAT_PASS_COUNT" "$UAT_FAIL_COUNT"
    if [[ "$UAT_PARTIAL" -eq 1 ]]; then
        printf '  %sPARTIAL RUN%s - a step filter was used, so this is not a full walkthrough\n' \
            "$UAT_YELLOW" "$UAT_NC"
    fi
    if [[ "$UAT_FAIL_COUNT" -eq 0 ]]; then
        if [[ "$UAT_STEPS_SKIPPED" -gt 0 ]]; then
            printf '  %sRESULT: PASS (%s step(s) skipped)%s\n' \
                "$UAT_YELLOW" "$UAT_STEPS_SKIPPED" "$UAT_NC"
        else
            printf '  %sRESULT: PASS%s\n' "$UAT_GREEN" "$UAT_NC"
        fi
        printf '====================================================================\n'
        return "$UAT_EXIT_OK"
    fi
    printf '  %sRESULT: FAIL%s\n' "$UAT_RED" "$UAT_NC"
    printf '====================================================================\n'
    return "$UAT_EXIT_FAIL"
}

# Resolved once at source time so uat_init stays cheap and project.sh can
# override UAT_REPO_ROOT without racing the lookup.
_UAT_DEFAULT_REPO_ROOT="$(_uat_find_repo_root)"

# Project hooks and overrides last: everything above is already defined, so
# project.sh can call any helper and override uat_seed / uat_cleanup.
if [[ -f "$UAT_LIB_DIR/project.sh" ]]; then
    # shellcheck source=/dev/null
    source "$UAT_LIB_DIR/project.sh"
fi
